example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist, show_xml, show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('html/', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('json/', show_json_todo, name='show_json_todo'),
    path('add/', create_task_ajax, name='create_task_ajax'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('create-task/', create_task, name='create_task'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models


class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.CharField(max_length=255)
    review = models.CharField(max_length=255)

todolist/models.py
from django.contrib.auth.models import User
from django.db import models


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

todolist/forms.py
from django.forms import ModelForm
from todolist.models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_barang_katalog,
        'nama': 'Joselin Permata Aprillia',
        'npm': '2106705410'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from mywatchlist.models import MyWatchList


def show_watchlist(request):
    data_film = MyWatchList.objects.all()
    context = {
        'list_film': data_film,
        'nama': 'Joselin Permata Aprillia',
        'npm': '2106705410'
    }
    return render(request, "mywatchlist.html", context)


def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
import datetime
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from todolist.models import Task
from todolist.forms import TaskForm


@login_required(login_url='/todolist/login/')
def show_todolist(request):
    list_task = Task.objects.filter(user=request.user)
    context = {
        'user': request.user,
        'list_task': list_task,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')

    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))  # membuat response
            # membuat cookie last_login dan menambahkannya ke dalam response
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


@login_required(login_url='/todolist/login/')
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response


@login_required(login_url='/todolist/login/')
def create_task(request):
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    context = {'form': form}
    return render(request, 'createtask.html', context)


@login_required(login_url='/todolist/login/')
def show_json_todo(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task.objects.create(user=request.user, date=datetime.date.today(), title=title, description=description)
        data = {
                'pk': task.pk,
                'fields': {
                    'user': task.user,
                    'date': task.date,
                    'title': task.title,
                    'description': task.description,
                }}
        return JsonResponse(data)
    return HttpResponseBadRequest()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.item_name}}</th>
            <th>{{barang.item_price}}</th>
            <th>{{barang.item_stock}}</th>
            <th>{{barang.rating}}</th>
            <th>{{barang.description}}</th>
            <th>{{barang.item_url}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <h4 id="bonus"></h4>

   <script>
       let sudah = 0;
       let belum = 0;
       {% for film in list_film %}
           {% if film.watched is True %}
               sudah = sudah + 1;
           {% else %}
               belum = belum + 1;
           {% endif %}
       {% endfor %}

       if (sudah > belum) {
           document.getElementById("bonus").innerHTML = "Selamat, kamu sudah banyak menonton!";
       } else {
           document.getElementById("bonus").innerHTML = "Wah, kamu masih sedikit menonton!";
       }
   </script>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Rating</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in list_film %}
        <tr>
            <td>{{film.watched}}</td>
            <td>{{film.title}}</td>
            <td>{{film.rating}}</td>
            <td>{{film.release_date}}</td>
            <td>{{film.review}}</td>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Todolist by Joselin</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,600">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    {% block meta %}
    {% endblock meta %}

    <style>
        body {
            background-color: #00DBDE;
            background-image: linear-gradient(90deg, #00DBDE 0%, #FC00FF 100%);
            font-family: 'Open Sans', sans-serif;
            font-size: 15px;
            font-weight: 400;
            color: #fff;
            line-height: 30px;
            text-align: center;
        }

        h1 {
            font-family: 'Open Sans Semibold', sans-serif;
            font-size: 50px;
            font-weight: bold;
            color: #fff;
            line-height: 46px;
        }

        h3 {
            font-family: 'Open Sans Semibold', sans-serif;
            font-size: 27px;
            font-weight: bold;
            color: #fff;
            line-height: 46px;
        }

        a {
            color: #fff;
            border-bottom: 1px dashed #fff;
        }

        a:hover, a:focus {
            color: #fff;
            border: 0;
            text-decoration: none;
        }

        .form-group {
            text-align: left;
        }

        p {
            color: #fff;
            color: rgba(255, 255, 255, 0.8);
        }

        p.description {
            margin-bottom: 20px;
        }

        p.copyright {
            margin-top: 40px;
        }

        .card{
            box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
            transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
            cursor: pointer;
        }

        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
        }
    </style>
</head>

<body class="h-100">
    {% block content %}
    {% endblock content %}
</body>

</html>

todolist/templates/createtask.html
{% extends 'base.html' %}

{% block meta %}

    <title>Tambah Task</title>

{% endblock meta %}

{% block content %}
    <div class="container h-100 w-25">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-10 col-md-8 col-lg-6">
                <form class="form-example" method="POST" action="">
                    {% csrf_token %}
                    <h3>Buat Task</h3>

                    <div class="form-group">
                        <label>Judul task:</label>
                        <div class="margin-left">{{ form.title }}</div>
                    </div>
                    <div class="form-group">
                        <label>Deskripsi Task:</label>
                        <div class="margin-left">{{ form.description }}</div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-customized" value="Buat Task">Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-10 col-md-8 col-lg-6">

                <form class="form-example" method="POST" action="">
                    {% csrf_token %}
                    <h1>Login</h1>
                    <p class="description">Silahkan login terlebih dahulu.</p>

                    <div class="form-group">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control username" id="username" placeholder="Username" name="username">
                    </div>

                    <div class="form-group">
                        <label for="password">Password:</label>
                        <input type="password" class="form-control password" id="password" placeholder="Password" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary btn-customized" value="Login">Login</button>
                </form>

            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <p class="copyright"> {{ message }}</p>
                    {% endfor %}
                </ul>
            {% endif %}

                <p class="copyright"> Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a></p>
            </div>
        </div>
    </div>


{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

<style>
    .login {
        padding-top: 20px;
    }
</style>

{% block content %}

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-10 col-md-8 col-lg-6">

                <form class="form-example" method="POST" action="">
                    {% csrf_token %}
                    <h1>Sign in</h1>
                    <p class="description">Silahkan buat akun terlebih dahulu.</p>

                    <div class="form-group">
                        {{ form.as_table }}
                    </div>
                    <input type="submit" class="btn btn-primary btn-customized" name="submit" value="Daftar"/>
                </form>

            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <p class="copyright"> {{ message }}</p>
                    {% endfor %}
                </ul>
            {% endif %}
            </div>
        </div>
    </div>


{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<script>
    const addCard = (task) => {
        $("#daftar_task").append(`
        <div class="card bg-light mb-3" style="max-width: 50rem; color:black;">
            <div class="card-header">Tanggal: ${task.fields.date}</div>
            <div class="card-body">
                <h4 class="card-title">${task.fields.title}</h4>
                <p style="color:black;" class="card-text">${task.fields.description}</p>
                <button class="btn btn-primary">Hapus Task</button>
            </div>
        </div>`);
    }

    var addTask = function() {
        var taskCards = $("#add-task").serialize();

        if ($("#title").val() && $("#description").val()) {
            $.ajax({ type: "POST", data: taskCards, url: "/todolist/add/", dataType: "json", encode: true,}).
                done(function (data) {
                    addCard(data);
                $("#add-task").trigger("reset");
                })
        }
    }

    $.getJSON('/todolist/json/', function(data) {
        data.forEach(task => {
            addCard(task);
        });
    });
</script>
{% endblock meta %}

{% block content %}
<style>
    .todo {
        padding-top: 100px;
        padding-bottom: 100px;
    }
</style>

<div class="todo">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-10 col-md-8 col-lg-6">
                <h1>Todo List</h1>
                    <p class="description">Halo, {{user}}!</p>

                    <!-- Button untuk trigger modal -->
                    <div> <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                            + Tambah Task baru (Modal) </button>
                        <a href="{% url 'todolist:create_task' %}">
                        <button class="btn btn-primary btn-customized">
                            + Tambah Task Baru</button>
                        </a>
                    </div>
                    <p><br></p>

                        <!-- Modal -->
                        <div class="modal fade" id="myModal" style="color:black;">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h5 class="modal-title">Tambah task</h5>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>

                                    <!-- Modal body -->
                                    <form method="POST" action="" id="add-task" class="p-3 m-0 border-0 bd-example" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <label for="title" class="col-form-label" style="float: left;">Judul Task:</label>
                                            <input type="text" class="form-control" id="title" name="title">
                                        </div>
                                        <div class="mb-3">
                                            <label for="description" class="col-form-label" style="float: left;">Deskripsi:</label>
                                            <textarea class="form-control" id="description" name="description"></textarea>
                                        </div>

                                    <!-- Modal footer -->
                                    <div class="modal-footer">
                                        <button type="submit" name="submit" onclick="addTask()" class="btn btn-primary" data-bs-dismiss="modal">Buat task</button>
                                    </div>
                                    </form>

                                </div>
                            </div>
                        </div>

                <div class="grid lg:grid-cols-4 md:grid-cols-3 gap-5 mt-8 sm:mt-5" id="daftar_task">
                </div>

                   {% for task in list_task %}
                        <div class="card bg-light mb-3" style="max-width: 50rem; color:black;">
                            <div class="card-header">Tanggal: {{task.date.date}}</div>
                            <div class="card-body">
                                <h4 class="card-title">{{task.title}}</h4>
                                <p style="color:black;" class="card-text">{{task.description}}</p>
                            </div>
                        </div>
                    {% endfor %}

                <p class="description">Sesi terakhir login: {{ last_login }}</p>

                <a href="{% url 'todolist:logout' %}"><button class="btn btn-primary btn-customized">Logout</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}